// This file was auto-generated by ML.NET Model Builder. 

using FasterrCNNResnet50_Detect_Image;
using Microsoft.ML.Data;

// Create single instance of sample data from first line of dataset for model input
var image = MLImage.CreateFromFile(@"..\\..\\..\\ImageInput.jpg");
AzureObjectDetection.ModelInput sampleData = new AzureObjectDetection.ModelInput()
{
    ImageSource = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = AzureObjectDetection.Predict(sampleData);
Console.WriteLine("Predicted Boxes:");
Console.WriteLine(predictionResult);
Console.WriteLine("Press ENTER to exit");
Console.ReadLine();

